apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
## these are replicaset labels
  labels:
    purpose: tolerations-demo
    project: roboshop
spec:
  replicas: 1
  selector:
  ## these labels sre used to select the pods
    matchLabels:
      purpose: tolerations-demo
      project: roboshop
  
### pod definition
  template:
    metadata:
      labels:
        purpose: tolerations-demo
        project: roboshop
    
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-23-59.ec2.internal
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effect: "NoSchedule"